from __future__ import annotations

from math import isfinite
from statistics import median
from typing import Any, Mapping
import logging

# ####################################################
# code generated by: chatgpt
# archietcted by Dave Brace

"""
price_shock.py

Calculates how abnormal today's stock price movement is relative
to the stock's normal historical daily price movement.

INPUT:

    {
        "current_price": float,
        "previous_close": float,
        "historical_closes": list[float],
    }

OUTPUT:

    {
        "price_return": float,
        "price_shock_zscore": float,
        "price_shock_score": float,
    }

The calculator does not use news, sentiment, volume, VWAP, or
intraday bars. Its only responsibility is identifying whether
today's price movement is unusually large for this stock.
"""

# #####################################################

class PriceShockCalculator:
    """
    Calculate an abnormal-price-movement score.

    The calculation uses:

        1. Today's return versus previous close.
        2. Historical daily returns.
        3. Median absolute movement as the normal baseline.
        4. Median Absolute Deviation (MAD) for a robust measure
           of how much daily movement normally varies.

    price_shock_score is normalized to 0.0 - 1.0.
    """

    DEFAULT_LOOKBACK = 60
    MAD_SCALE = 1.4826
    ZSCORE_CAP = 5.0

    def __init__(
        self,
        lookback: int = DEFAULT_LOOKBACK,
        zscore_cap: float = ZSCORE_CAP,
    ) -> None:

        if lookback < 10:
            raise ValueError(
                "lookback must be at least 10"
            )

        if zscore_cap <= 0:
            raise ValueError(
                "zscore_cap must be greater than zero"
            )

        self.lookback = lookback
        self.zscore_cap = zscore_cap
    
    # ##############################

    def calculate(
        self,
        price_data: Mapping[str, Any],
    ) -> dict[str, float]:
        """
        Calculate today's price shock.

        REQUIRED INPUT STRUCTURE:

            price_data = {
                "current_price": float,
                "previous_close": float,
                "historical_closes": list[float],
            }

        Example:

            price_data = {
                "current_price": 235.68,
                "previous_close": 233.69,
                "historical_closes": [
                    228.41,
                    229.17,
                    227.93,
                    231.04,
                    ...
                ],
            }

        historical_closes should contain at least 10 valid
        prior trading-session closing prices. 60 is recommended.

        RETURNS:

            {
                "price_return": 0.008526,
                "price_shock_zscore": 1.3724,
                "price_shock_score": 0.2745,
            }
        """

        current_price = self._positive_float(
            price_data.get("current_price"),
            "current_price",
        )

        previous_close = self._positive_float(
            price_data.get("previous_close"),
            "previous_close",
        )

        historical_closes = self._clean_prices(
            price_data.get("historical_closes")
        )

        if len(historical_closes) < 10:
            raise ValueError(
                "historical_closes must contain at least "
                "10 valid prior trading-session closes"
            )

        # ---------------------------------------------------------
        # 1. Today's actual price movement.
        # ---------------------------------------------------------

        price_return = (
            current_price - previous_close
        ) / previous_close

        # ---------------------------------------------------------
        # 2. Calculate historical daily returns.
        #
        # If historical_closes is:
        #
        #     [230, 232, 231, 235]
        #
        # returns become:
        #
        #     +0.87%
        #     -0.43%
        #     +1.73%
        # ---------------------------------------------------------

        historical_returns = []

        for previous, current in zip(
            historical_closes,
            historical_closes[1:],
        ):
            if previous <= 0:
                continue

            historical_returns.append(
                (current - previous) / previous
            )

        if len(historical_returns) < 10:
            raise ValueError(
                "Not enough valid historical daily returns"
            )

        # Only use the most recent lookback returns.
        historical_returns = historical_returns[
            -self.lookback:
        ]

        # ---------------------------------------------------------
        # 3. We are measuring SIZE of movement, not direction.
        #
        # Direction remains available in price_return.
        #
        # +3% and -3% are both large price shocks.
        # ---------------------------------------------------------

        historical_moves = [
            abs(value)
            for value in historical_returns
        ]

        today_move = abs(price_return)

        # ---------------------------------------------------------
        # 4. Establish normal movement.
        #
        # Median is used instead of mean because it is much less
        # affected by historical earnings/news shocks.
        # ---------------------------------------------------------

        median_move = median(
            historical_moves
        )

        # ---------------------------------------------------------
        # 5. Calculate Median Absolute Deviation (MAD).
        # ---------------------------------------------------------

        deviations = [
            abs(value - median_move)
            for value in historical_moves
        ]

        mad = median(deviations)

        # ---------------------------------------------------------
        # 6. Convert MAD into a standard-deviation-like scale.
        #
        # 1.4826 is the standard normal consistency factor.
        # ---------------------------------------------------------

        if mad > 0:
            scale = self.MAD_SCALE * mad
        else:
            # Extremely stable stocks can have MAD == 0.
            # Use the median movement as a conservative fallback.
            scale = max(
                median_move * self.MAD_SCALE,
                1e-6,
            )

        # ---------------------------------------------------------
        # 7. Calculate robust z-score.
        #
        # 0.0 means today's movement is approximately normal.
        #
        # Larger positive values mean increasingly abnormal
        # movement.
        # ---------------------------------------------------------

        price_shock_zscore = (
            today_move - median_move
        ) / scale

        # A movement below the historical normal level is not
        # considered a price shock.
        price_shock_zscore = max(
            price_shock_zscore,
            0.0,
        )

        # ---------------------------------------------------------
        # 8. Normalize z-score to 0.0 - 1.0.
        #
        # z = 0 -> 0.00
        # z = 1 -> 0.20
        # z = 2 -> 0.40
        # z = 3 -> 0.60
        # z = 4 -> 0.80
        # z = 5 -> 1.00
        # z > 5 -> 1.00
        # ---------------------------------------------------------

        price_shock_score = min(
            price_shock_zscore / self.zscore_cap,
            1.0,
        )

        return {
            "price_return": round(
                price_return,
                6,
            ),
            "price_shock_zscore": round(
                price_shock_zscore,
                4,
            ),
            "price_shock_score": round(
                price_shock_score,
                4,
            ),
        }

    @staticmethod
    def _clean_prices(
        prices: Any,
    ) -> list[float]:
        """
        Remove invalid historical prices.
        """

        if prices is None:
            return []

        if isinstance(prices, (str, bytes)):
            return []

        try:
            iterator = iter(prices)
        except TypeError:
            return []

        cleaned = []

        for value in iterator:
            try:
                value = float(value)
            except (TypeError, ValueError):
                continue

            if (
                isfinite(value)
                and value > 0
            ):
                cleaned.append(value)

        return cleaned

    @staticmethod
    def _positive_float(
        value: Any,
        name: str,
    ) -> float:
        """
        Validate a required positive numeric input.
        """

        try:
            value = float(value)
        except (TypeError, ValueError):
            raise ValueError(
                f"{name} must be numeric"
            )

        if (
            not isfinite(value)
            or value <= 0
        ):
            raise ValueError(
                f"{name} must be greater than zero"
            )

        return value